#!/usr/bin/python
from lasp.lasp_playback import Playback
import argparse

parser = argparse.ArgumentParser(
    description='Playback recorded measurement'
)
parser.add_argument('filename', help='Filename of measurement', type=str)
args = parser.parse_args()
p = Playback(args.filename)
p.start()
